#2020-08

大部分编程语言不区分错误的类型，但是Rust会。Rust把错误分为两类：
- recoverable Error，在`Result<T, E>`中表示
- uncoverable Error，用`panic!`来表示

# 9.1 `panic!`

## unwinding the stack vs aborting
如下配置可以让程序在 panic 时直接退出而不清栈
```
[profile.release] <--- 写在 Cargo.toml 中
panic = 'abort'
```
#TODO 如果没有这个，默认行为是怎样的？

## panic时让程序打印调用栈
`RUST_BACKTRACE=1 cargo run`

需要编译时保留symbol，所以不能有 `--release`，如 `cargo build --release`这样是不行的。

# 9.2 `Result`中的错误信息

## `Result`基础
```
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

一个普通的例子:
``` rust
use std::fs::File;

fn main() {
    let f = match File::open("hello.txt") {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error), // <--- 当然也可以是别的处理
    };
}
```

一个复杂一点的例子：
``` rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = match File::open("hello.txt") {
        Ok(file) => file,
        Err(error) => match error.kind() {                            // <--- match ... {} 是一个 expression，所以可以这么搞...
            ErrorKind::NotFound => match File::create("hello.txt") {  // <--- match ... {} 是一个 expression，所以可以这么搞...
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => panic!("Problem opening the file: {:?}", other_error)
        }
    };
}
```

#TODO understand this example:
``` rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```

## `unwrap` & `expect`
``` rust
let f = match File::open("hello.txt") {
    Ok(file) => file,
    Err(error) => panic!("abcd"), // <--- 这里没有用到 error 变量
};
```

可以用`expect`简写成：
``` rust
let f = File::open("hello.txt").expect("abcd"); // <--- 这里没有用到错误error的具体信息
```

如果不需要"abcd"那个字符串，那么还可以用`unwrap`进一步简写成：
``` rust
let f = File::open("hello.txt").unwrap();
```

## 往上层回传错误
用返回`Result<T, E>`来传递信息。
``` Rust
fn foo() -> Result<Type, Error> {
    ...
    match xxx {
        Err(e) => return Err(e), // <--- 提前返回错误。注意这里返回的是 Err 的 enum
        Ok(x) => x,
    }
	
	...

    return Ok(...);              // <--- 正常返回错误。注意这里返回的是 Ok 的 enum
}
```

如果我们不需要对错误e进行处理，仅仅是往回抛，那么可以用语法糖 `?`:
``` Rust
fn foo() -> Result<Type, Error> {
    ...
	xxx?;            // <--- 只需在Result后加问号，可提前返回错误。返回的是 Err 的 enum
	...

    return Ok(...);  // <--- 正常返回错误。注意这里返回的是 Ok 的 enum
}
```

还可以有这种技巧：
``` rust
foo()?.bar()?; // <--- 假设 foo() 和 bar() 都返回 Result
```

但是`?`要求所在函数的返回类型是 `std::ops::Try` Trait，比如 `Result`, `Option`.

#TODO 看明白这个:
``` rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;

    Ok(())
}
```

# 9.3 要不要 `panic!` ?
这个就是要不要让程序崩溃的常见问题。